In [1]:
import numpy as np
a = np.array([1, 3, 2])
b = np.array([4, 8, 5])
a_b_cross = np.cross(a, b)
c = np.array([3, 5, 6])
d = np.array([4, 7, 1])
c_d_cross = np.cross(c, d)
a_c = np.vstack((a, c))
b_d = np.vstack((b, d))
cross = np.cross(a_c, b_d)
print(a_b_cross)
print(c_d_cross)
print(cross)

[-1  3 -4]
[-37  21   1]
[[ -1   3  -4]
 [-37  21   1]]


In [4]:
a_b_dot = np.dot(a, b)
c_d_dot = np.dot(c, d)
dot = np.sum(a_c*b_d, axis=1)
print(a_b_dot)
print(c_d_dot)
print(dot)

38
53
[38 53]
